### PR TITLE
Add `Changelog` support

### PR DESCRIPTION
**Pull request by jbesta**
Provide list of changelog entries for generated RPM.

https://docs.fedoraproject.org/en-US/Fedora_Draft_Documentation/0.1/html/RPM_Guide/ch22s05.html

### CODE REVIEW

**Comment by jbesta** [comment]
@rictorres Any news on this pull request? Are there any issues regarding integration to the codebase?

**Comment by rictorres** [comment]
@jbesta i think there are some conflicts in here. do you wanna fix them or should i? thanks!

**Comment by jbesta** [comment]
@rictorres I will take a look at it and update pull request

**Comment by jbesta** [comment]
@rictorres I've resolved conflicts and updated pull request. everything should be ok now.

**Pull request merged**
